"""Default chat intents config.

Hardcoded fallback used when a project has no `.eurika/config/chat_intents.yaml`
(or no `docs/chat_intents.example.yaml`). Lets factual intents like greeting,
project_overview, file_recount, project_tree work for any external project
without copying a YAML file.

User-provided `.eurika/config/chat_intents.yaml` is merged on top
(per-intent override, top-level keys overridden as-is).
"""
from __future__ import annotations

from typing import Any, Dict

from eurika.api.chat_identity import IDENTITY_REGEX_PATTERNS

DEFAULT_CONFIG: Dict[str, Any] = {
    "version": 1,
    "vector_min_similarity": 0.72,
    "intent_hints": (
        "- Команды: «покажи структуру», «сколько файлов?», «что за проект?», «что дальше по развитию?», «покажи отчёт».\n"
        "- Цель агента: «какая цель?», «что получилось?», «итог цели», «сбрось цель».\n"
        "- Market: «анализ рынка» — сейчас; «логика маркета» — как устроен paper ML; "
        "«пока меня не было» — digest; «одна модель или на каждый тикер?» — scope ML.\n"
        "- Скан: «просканируй проект» (eurika scan .).\n"
        "- Ритуал: «проведи ритуал» (scan → doctor → report-snapshot).\n"
        "- Smoke: «проведи smoke test» (torch + Qt smoke).\n"
        "- Коммит: «собери коммит», подтверждение «применяй»."
    ),
    "intents": {
        "identity": {
            "match_mode": "regex",
            "patterns": list(IDENTITY_REGEX_PATTERNS),
        },
        "greeting": {
            "match_mode": "regex",
            "patterns": [
                r"^\s*привет[!.…]*\s*$",
                r"^\s*здравствуй",
                r"^\s*добрый\s+(день|вечер|утро)",
                r"^\s*доброе\s+утро",
                r"^\s*hello[!.]*\s*$",
                r"^\s*hi[!.]*\s*$",
                r"^\s*hey[!.]*\s*$",
                r"^\s*good\s+(morning|evening|afternoon)",
            ],
        },
        "capabilities": {
            "match_mode": "regex",
            "patterns": [
                r"^\s*что\s+ты\s+умеешь\??\s*$",
                r"^\s*что\s+умеешь\??\s*$",
                r"^\s*что\s+ты\s+можешь\??\s*$",
                r"^\s*что\s+можешь\??\s*$",
                r"^\s*чем\s+можешь\s+помочь\??\s*$",
                r"^\s*какие\s+команды\??\s*$",
                r"^\s*справка\s*$",
                r"^\s*помощь\s*$",
                r"^\s*help\s*$",
                r"^\s*what\s+can\s+you\s+do\??\s*$",
                # Capability probes that otherwise fall through to weak LLM.
                r"ты\s+можешь\s+писать",
                r"умеешь\s+писать",
                r"можешь\s+писать\s+(программ|код|скрипт)",
                r"умеешь\s+писать\s+(программ|код|скрипт)",
                r"пишешь\s+код",
                r"пишешь\s+программ",
                r"can\s+you\s+write\s+(code|programs?|scripts?)",
                r"do\s+you\s+write\s+(code|programs?)",
                r"can\s+you\s+code\??\s*$",
                # Local shell / system access (must not fall to web_search).
                r"доступ\s+к\s+систем",
                r"системн\w*\s+команд",
                r"доступ\s+к\s+терминал",
                r"есть\s+доступ\s+к\s+(систем|терминал|shell)",
                r"можешь\s+выполнять\s+команд",
                r"умеешь\s+выполнять\s+команд",
                r"можешь\s+запускать\s+команд",
                r"выполнять\s+системн",
                r"запускать\s+shell",
                r"есть\s+ли\s+терминал",
                r"can\s+you\s+run\s+(commands?|shell|terminal)",
                r"do\s+you\s+have\s+access\s+to\s+(the\s+)?(system|shell|terminal)",
                r"access\s+to\s+(the\s+)?(system|shell|terminal)",
            ],
        },
        "roadmap_next": {
            "match_mode": "regex",
            "patterns": [
                r"дальше\s+по\s+развит",
                r"что\s+(?:у\s+нас\s+)?дальше",
                r"следующ\w*\s+шаг",
                r"развит\w+\s+проект",
                r"план\s+развит",
                r"\broadmap\b",
                r"из\s+roadmap",
                r"по\s+roadmap",
                r"просмотр\w*\s+roadmap",
                r"что\s+в\s+roadmap",
                r"открыт\w+\s+бэклог",
            ],
        },
        "project_overview": {
            "patterns": [
                "что за проект",
                "что это за проект",
                "что это за",
                "опиши проект",
                "расскажи о проекте",
                "расскажи про проект",
                "какой это проект",
                "какой проект",
                "describe the project",
                "about this project",
                "what is this project",
            ],
        },
        "goal_status": {
            "patterns": [
                "какая цель",
                "какая сейчас цель",
                "что в контексте",
                "что в контексте агента",
                "покажи цель",
                "покажи активную цель",
                "статус цели",
                "active goal",
                "what is the goal",
                "what's the goal",
                "current goal",
                "show goal",
                "agent context",
            ],
            "exact": [
                "цель?",
                "цель",
                "контекст?",
                "контекст",
            ],
            "emit": None,
        },
        "goal_reflection": {
            "patterns": [
                "что получилось",
                "что получилось?",
                "итог цели",
                "итог выполнения",
                "результат цели",
                "как прошла цель",
                "reflection",
                "goal reflection",
                "what was the outcome",
                "what happened with the goal",
            ],
            "exact": [
                "что получилось",
                "что получилось?",
                "итог цели",
            ],
            "emit": None,
        },
        "clear_goal": {
            "patterns": [
                "сбрось цель",
                "сбросить цель",
                "очисти цель",
                "очистить цель",
                "забудь цель",
                "сбрось контекст цели",
                "очисти контекст агента",
                "clear goal",
                "reset goal",
                "clear active goal",
            ],
            "exact": [
                "сбрось цель",
                "очисти цель",
                "clear goal",
            ],
            "emit": None,
        },
        "file_recount": {
            "match_mode": "regex",
            "patterns": [
                r"сколько\s+(?:\w+\s+){0,6}файл",
                r"сколько\s+(?:\w+\s+){0,6}модул",
                r"how\s+many\s+(?:\w+\s+){0,4}files?",
                r"(?:пере|под|по)счита\w*\s+(?:\w+\s+){0,6}файл",
                r"\bпересчита",
                r"\bподсчита\w*\s+файл",
                r"\bпосчита\w*\s+файл",
                r"\bcount\s+files",
                r"\brecount\s+files",
            ],
        },
        "project_tree": {
            "patterns": [
                "покажи структ",
                "покажи дерево",
                "какая структура",
                "структуру проекта",
                "фактическую структуру",
                "дерево проекта",
                "дерево файлов",
                "project structure",
                "folder structure",
                "project tree",
            ],
            "emit": "$ eurika project-tree .",
        },
        "scan": {
            "patterns": [
                "просканируй",
                "прогони scan",
                "запусти scan",
                "сканируй проект",
                "eurika scan",
                "run scan",
            ],
            "exact": [
                "scan",
                "скан",
                "сканируй",
            ],
            # Skip when user is using run_command/show syntax that just *mentions* scan.
            "exclude": [
                "дерево",
                "структур",
                "выполни команд",
                "выполнить команд",
                "execute command",
                "run command",
            ],
            "emit": "$ eurika scan .",
        },
        "list_docs": {
            "patterns": [
                "какие документ",
                "какие есть документ",
                "какая документация",
                "документы по проекту",
                "документацию проекта",
                "найди документ",
                "найди документацию",
                "какие есть docs",
                "покажи документ",
                "покажи docs",
                "список документ",
                "список docs",
                "какие md",
                "какие markdown",
                "посмотреть документ",
                "show docs",
                "list docs",
                "show documentation",
                "list documentation",
                "what docs",
                "what documentation",
            ],
        },
        "web_search": {
            "patterns": [
                "найди в интернете",
                "поищи в интернете",
                "поиск в интернете",
                "интернет-поиск",
                "интернет поиск",
                "погугли",
                "загугли",
                "search the web",
                "web search",
                "search online",
                "find on the internet",
            ],
            "exclude": [
                "найди документ",
                "найди документацию",
                "документы по проекту",
            ],
        },
        "project_ls": {
            "patterns": [
                " ls ",
                "команду ls",
                "выполни ls",
                "run ls",
                "execute ls",
                "list root",
                "list files",
                "покажи файлы",
            ],
            "exact": ["ls"],
            "emit": "$ ls -la",
        },
        "smoke_test": {
            "patterns": [
                "проведи smoke",
                "прогони smoke",
                "запусти smoke",
                "выполни smoke",
                "smoke test",
                "smoke-test",
                "смоук тест",
                "проведи смоук",
                "qt smoke",
                "проведи qt smoke",
                "run smoke",
                "run smoke test",
            ],
            "exact": [
                "smoke",
                "smoke test",
                "смоук",
            ],
            "vector_exemplars": [
                "проведи smoke test",
                "запусти smoke",
                "run smoke test",
                "qt smoke",
            ],
            "emit": None,
        },
        "self_check": {
            "patterns": [
                "проведи self-check",
                "прогони self-check",
                "запусти self-check",
                "self-check",
                "self check",
                "проведи self check",
                "eurika self-check",
            ],
            "exact": ["self-check", "self check"],
            "emit": "$ eurika self-check .",
        },
        "ml_status": {
            "patterns": [
                "статус ml",
                "статус мл",
                "проверь статус ml",
                "проверь статус мл",
                "покажи статус ml",
                "ml статус",
                "ml status",
                "статус машинного обучения",
                "состояние ml",
            ],
            "exact": [
                "статус ML",
                "ML статус",
            ],
            "emit": None,
        },
        # Architecture of Market — before situation snapshot («что на рынке»).
        "market_logic": {
            "patterns": [
                "логика маркета",
                "логике маркета",
                "логики маркета",
                "логика рынка",
                "логике рынка",
                "логики рынка",
                "логика market",
                "логике market",
                "логика paper",
                "логике paper",
                "как устроен маркет",
                "как устроен market",
                "как устроен paper",
                "как работает маркет",
                "как работает market",
                "как работает paper",
                "как устроена торговля",
                "устройство маркета",
                "архитектура маркета",
                "архитектура market",
                "market logic",
                "how market works",
                "how the market works",
                "how does market work",
                "paper trading logic",
                "скелет маркета",
                "market ml цикл",
            ],
            "vector_exemplars": [
                "что скажешь о логике маркета в проекте?",
                "как устроен paper market ml?",
                "объясни архитектуру маркета",
                "how does the paper market loop work?",
                "скелет: свечи → фичи → MLP → paper → обучение",
            ],
            "emit": None,
        },
        # Before market_ml_scope — «анализ рынка сейчас» ≠ architecture question.
        "market_situation": {
            "patterns": [
                "анализ рынка",
                "анализ маркета",
                "ситуация на рынке",
                "ситуация в маркете",
                "ситуацию на рынке",
                "ситуацию в маркете",
                "что на рынке",
                "что на маркете",
                "что сейчас на рынке",
                "что сейчас на маркете",
                "как дела на рынке",
                "как дела на маркете",
                "как дела в маркете",
                "как на рынке",
                "как на маркете",
                "что по рынку",
                "что по маркету",
                "что с рынком",
                "что с маркетом",
                "рынок сейчас",
                "маркет сейчас",
                "что крутится",
                "сейчас в тебе крутится",
                "срез рынка",
                "срез маркета",
                "обзор рынка",
                "обзор маркета",
                "market situation",
                "market now",
                "how's the market",
                "how is the market",
                "what's the market",
                "what is the market doing",
            ],
            "vector_exemplars": [
                "проведи анализ рынка который сейчас крутится",
                "что сейчас на маркете / какая ситуация?",
                "как дела на маркете?",
                "как дела на рынке сейчас?",
                "срез paper market: банк, opens, советы модели",
                "market situation now: equity opens HOLD BUY SELL",
            ],
            "emit": None,
        },
        "session_digest": {
            "patterns": [
                "пока тебя не было",
                "пока меня не было",
                "что было пока",
                "какие новости пока",
                "новости пока меня",
                "новости пока тебя",
                "что пропустил",
                "что я пропустил",
                "дай digest",
                "session digest",
                "сводка сессии",
                "сводка за время",
            ],
            "vector_exemplars": [
                "что было пока меня не было?",
                "какие новости пока меня не было?",
                "пока тебя не было — краткий отчёт по paper",
                "session digest since last visit",
            ],
            "emit": None,
        },
        "market_ml_scope": {
            "patterns": [
                "стратегию каждого тикера",
                "каждого тикера в отдельности",
                "в целом для рынка",
                "по разным тикерам",
                "как учится market",
                "как учится ml на маркет",
                "одна модель на все",
                "отдельная модель на тикер",
                "per-ticker",
                "per ticker",
                "shared market model",
                "общая модель рынка",
                "общая policy",
                "market_policy",
            ],
            # Curated exemplars only — raw patterns like «каждого тикера…» falsely
            # match identity questions via embeddings (e.g. «кто тебя создал?»).
            "vector_exemplars": [
                "одна модель market ml на все тикеры или отдельно на каждый?",
                "учится стратегия каждого тикера или общая модель рынка?",
                "shared market_policy or per-ticker models",
                "market ml: общая policy или per ticker",
            ],
            "emit": None,
        },
        "vector_intent_on": {
            "patterns": [
                "включи eurika_use_vector_intent",
                "включи vector intent",
                "включи vector_intent",
                "enable vector intent",
                "eurika_use_vector_intent=1",
            ],
            "exact": [
                "включи EURIKA_USE_VECTOR_INTENT=1",
                "включи EURIKA_USE_VECTOR_INTENT",
                "EURIKA_USE_VECTOR_INTENT=1",
            ],
            "emit": None,
        },
        "vector_intent_off": {
            "patterns": [
                "выключи eurika_use_vector_intent",
                "выключи vector intent",
                "выключи vector_intent",
                "disable vector intent",
                "eurika_use_vector_intent=0",
            ],
            "exact": [
                "выключи EURIKA_USE_VECTOR_INTENT",
                "EURIKA_USE_VECTOR_INTENT=0",
            ],
            "emit": None,
        },
        "vector_intent_status": {
            "patterns": [
                "включен ли vector",
                "включён ли vector",
                "включен ли vector_intent",
                "включён ли vector_intent",
                "включен ли vector intent",
                "включён ли vector intent",
                "статус vector intent",
                "статус vector_intent",
                "статус eurika_use_vector_intent",
                "проверь vector intent",
                "проверь vector_intent",
                "vector intent включен",
            ],
            "exact": [
                "статус EURIKA_USE_VECTOR_INTENT",
                "EURIKA_USE_VECTOR_INTENT?",
                "VECTOR_INTENT?",
            ],
            "emit": None,
        },
        "ml_intent_on": {
            "patterns": [
                "включи eurika_use_ml_intent",
                "включи ml intent",
                "включи ml-intent",
                "включи ml роутер",
                "включи ml router",
                "enable ml intent",
                "enable eurika_use_ml_intent",
                "eurika_use_ml_intent=1",
                "eurika_use_ml_intent = 1",
            ],
            "exact": [
                "включи EURIKA_USE_ML_INTENT=1",
                "включи EURIKA_USE_ML_INTENT",
                "EURIKA_USE_ML_INTENT=1",
            ],
            "emit": None,
        },
        "ml_intent_off": {
            "patterns": [
                "выключи eurika_use_ml_intent",
                "выключи ml intent",
                "выключи ml-intent",
                "выключи ml роутер",
                "disable ml intent",
                "eurika_use_ml_intent=0",
            ],
            "exact": [
                "выключи EURIKA_USE_ML_INTENT",
                "EURIKA_USE_ML_INTENT=0",
            ],
            "emit": None,
        },
        "ml_intent_status": {
            "patterns": [
                "статус ml intent",
                "статус ml-intent",
                "статус ml_intent",
                "статус eurika_use_ml_intent",
                "ml intent status",
                "проверь ml intent",
                "проверь ml-intent",
                "проверь ml_intent",
                "проверь eurika_use_ml_intent",
                "включен ли ml intent",
                "включён ли ml intent",
                "включен ли ml_intent",
                "включён ли ml_intent",
                "включен ли eurika_use_ml_intent",
                "включён ли eurika_use_ml_intent",
                "включен ли ml",
                "включён ли ml",
                "ml_intent включен",
                "ml intent включен",
                "работает ли ml intent",
            ],
            "exact": [
                "статус EURIKA_USE_ML_INTENT",
                "EURIKA_USE_ML_INTENT?",
                "ML_INTENT?",
                "ml_intent?",
            ],
            "emit": None,
        },
    },
}
