"""DRILL_REFACTOR_CODE_SMELL_FORMAT_CHAIN: long_function — цепочка форматирования строк.

Последовательные f-strings или format() без блоков. Вариант для LLM: extract template
или _build_message helper.
"""


def polygon_refactor_code_smell_format_chain(name: str, count: int, items: list) -> str:
    """55+ строк: построение длинного сообщения через конкатенацию/форматирование."""
    parts = []
    parts.append(f"Hello, {name}")
    parts.append(f"Count: {count}")
    parts.append(f"Items: {len(items)}")
    parts.append(f"First: {items[0] if items else 'N/A'}")
    parts.append(f"Last: {items[-1] if items else 'N/A'}")
    parts.append(f"Sum: {sum(items) if items else 0}")
    parts.append(f"Min: {min(items) if items else 0}")
    parts.append(f"Max: {max(items) if items else 0}")
    parts.append(f"Avg: {sum(items) / len(items) if items else 0}")
    parts.append(f"Range: {max(items) - min(items) if items else 0}")
    parts.append(f"Status: {'ok' if items else 'empty'}")
    parts.append(f"Mode: {'batch' if count > 1 else 'single'}")
    parts.append(f"Total: {count * len(items) if items else 0}")
    parts.append(f"Chunk: {count}")
    parts.append(f"Size: {len(str(items))}")
    parts.append(f"Type: {type(items).__name__}")
    parts.append(f"Len: {len(items)}")
    parts.append(f"Hash: {hash(tuple(items)) if items else 0}")
    parts.append(f"Repr: {repr(items)[:50]}")
    parts.append(f"Str: {str(items)[:50]}")
    parts.append(f"Bool: {bool(items)}")
    parts.append(f"None check: {items is not None}")
    parts.append(f"Empty: {not items}")
    parts.append(f"Sorted: {sorted(items)[:3] if items else []}")
    parts.append(f"Reversed: {list(reversed(items))[:3] if items else []}")
    parts.append(f"Unique: {len(set(items)) if items else 0}")
    parts.append(f"Index 0: {items[0] if len(items) > 0 else None}")
    parts.append(f"Index -1: {items[-1] if len(items) > 0 else None}")
    parts.append(f"Slice [0:3]: {items[0:3] if items else []}")
    parts.append(f"Slice [-3:]: {items[-3:] if items else []}")
    parts.append(f"Has 0: {0 in items if items else False}")
    parts.append(f"Has -1: {-1 in items if items else False}")
    parts.append(f"All positive: {all(x > 0 for x in items) if items else True}")
    parts.append(f"Any zero: {any(x == 0 for x in items) if items else False}")
    parts.append(f"Filtered: {[x for x in items if x > 0][:5] if items else []}")
    parts.append(f"Mapped: {[x * 2 for x in items][:5] if items else []}")
    parts.append(f"Reduced: {sum(items) if items else 0}")
    parts.append(f"Joined: {','.join(str(x) for x in items[:5]) if items else ''}")
    parts.append(f"Splitted: {len(str(items).split(','))}")
    parts.append(f"Replaced: {str(items).replace('[', '')[:20] if items else ''}")
    parts.append(f"Strip: {str(items).strip()[:20] if items else ''}")
    parts.append(f"Upper: {name.upper()}")
    parts.append(f"Lower: {name.lower()}")
    parts.append(f"Title: {name.title()}")
    # Padding to exceed MAX_FUNCTION_LINES (50)
    parts.append("_pad1")
    parts.append("_pad2")
    parts.append("_pad3")
    parts.append("_pad4")
    parts.append("_pad5")
    parts.append("_pad6")
    parts.append("_pad7")
    parts.append("_pad8")
    parts.append("_pad9")
    parts.append("_pad10")
    return " | ".join(parts)
